# @package _global_

model_type: CAUSAL

model:
  _target_: transformers.AutoModelForCausalLM.from_pretrained
  pretrained_model_name_or_path: EleutherAI/pythia-70m
  attention_dropout: 0.1
  hidden_dropout: 0.1
  classifier_dropout: 0.1

tokenizer:
  _target_: transformers.AutoTokenizer.from_pretrained
  pretrained_model_name_or_path: EleutherAI/pythia-70m